### ISSUE TITLE
GitLab to GitHub: Link Usernames to Match Contributions

### ISSUE THREAD

**Issue by EZoni** [selalib/selalib#13]
Hi all, I'm glad to see that SeLaLib landed on GitHub.

I was wondering if it would be possible, for those of you who still have access to the old GitLab repository and who took care of the migration from GitLab to GitHub, to make sure that the old usernames/users on GitLab are linked to the correct usernames/users on GitHub. So that one's contributions actually show up in one's GitHub profile correctly.

This is a random example of a commit of mine, three years ago: https://github.com/selalib/selalib/commit/df8491e97aeb7ba2b13eee77914b963e713319e5 (found through `blame` by looking at the source code directly). It reads "Edoardo Zoni committed..." but the author of the commit is not linked to any GitHub user. That should read "EZoni committed..." instead, because @EZoni is my correct GitHub username (in which case one would be allowed to click on the username "EZoni" to "view all commits by EZoni", copying GitHub's own language).

I think it would be good if we could make sure that everyone's contributions are counted correctly, since this is open-source now. Please let me know what you think and if I can provide more information in order to help fix the issue. I do not have access to my old GitLab account through MPCDF, so I will not be able to gather any information from there, unless I contact the help desk directly.

Thanks in advance!

**Comment by pnavaro** [comment]
Hi Edoardo, did you try to add the email you used back then as secondary email in your GitHub profile ?
 But there is a possibility to rewrite the history and change  the email to mach the github one.
I will try to do this.

**Comment by EZoni** [comment]
Hi Pierre, thank you. I have just added my old MPCDF email as secondary email in my GitHub profile, but I will not be able to verify it, because the email address was deactivated last year. So I'm not sure if this alone will fix the issue.

**Comment by pnavaro** [comment]
Could you send me your github email address. I will change it in the history.

**Comment by EZoni** [comment]
I just sent you an email (University of Rennes address) with my GitHub primary email address. Thank you again for looking into this.

**Comment by pnavaro** [comment]
OK Edoardo, It is good now. Have a nice weekend !

**Comment by EZoni** [comment]
Thank you so much for the fix, Pierre!
