### ISSUE TITLE
Precision tests and portability

### ISSUE THREAD

**Issue by kkormann** [selalib/selalib#16]
Two test use integers of kind 16 not available on all systems:

`low_level_utilities/working_precision/testing/test_working_precision.F90`
`low_level_utilities/utilities/testing/test_utilities.F90`

**Comment by pnavaro** [comment]
Are we using integers of kind 16 in the code ?  I think not. I did not find the "_i16" . I think I could remove these tests.

**Comment by kkormann** [comment]
`f2 = transfer(int(z'7fefffffffffffff', kind=16), f2) ! largest IEEE-754 double float
   small2 = transfer(int(z'7feffffffffffff1', kind=16), small2)
`

**Comment by kkormann** [comment]
This is line 52-53 in `low_level_utilities/working_precision/testing/test_working_precision.F90`

**Comment by pnavaro** [comment]
I think it could be replace by

```fortran
small2 = tiny(small2)
f2 = huge(f16)
```
I am trying

**Comment by kkormann** [comment]
Thanks!
