### ISSUE TITLE
HDF5 configuration on Ubuntu

### ISSUE THREAD

**Issue by kkormann** [selalib/selalib#30]
It appears that the latest version of selalib tends to set the "HDF5_IS_PARALLEL" to false, also if I set the "HDF5_ROOT" to the path of the parallel HDF library on Ubuntu. @pnavaro Do you have an idea why this is?
This causes the simulations not to be build as @paulwilhemvlasov pointed out to me. The problem does not occur for the  f12cae55183f74dec67425d72ed99f9c2e7d8aac.

**Comment by pnavaro** [comment]
Hello Katharina. Strange because I set it to true by default initially. I am looking at this.

**Comment by kkormann** [comment]
> Hello Katharina. Strange because I set it to true by default initially. I am looking at this.

Thanks!

**Comment by pnavaro** [comment]
The cmake config was changed this summer. We use the internal [FindHDF5](https://cmake.org/cmake/help/latest/module/FindHDF5.html) now.  I set the variable `HDF5_PREFER_PARALLEL` to `TRUE`. I hop it fixes the problem. I can add a test to check if the HDF5 library found is really parallel.

**Comment by pnavaro** [comment]
I think it is probably better to raise an error if we don't find the parallel version.

**Comment by pnavaro** [comment]
Ok I refactor the HDF5 cmake config, is it better ?

**Comment by kkormann** [comment]
Thanks, @pnavaro, now it works again!
